### ISSUE TITLE
The eccentricity equation in two files is incorrect

### ISSUE THREAD

**Issue by rmkar** [jeremy-penn/Orbital_Mechanics#3]
I was going through this repo and I noticed that the eccentricity equations in `coe_from_rv` and `kepler_convert` are incorrect compared to those listed in Curtis's textbook.
The current equation is `E = (1 / mu)*((v^2 - (mu / r))*R - vr*V);`
Whereas the equation according to the textbook is `E = (1 / mu)*((v^2 - (mu / r))*R - r*vr*V);`

The equation in the file is missing the position vector in the last term.

**Comment by jeremy-penn** [comment]
I believe the equation in Curtis is incorrect in some editions. The equation in Curtis you've correctly given does not have correct units for eccentricity (dimensionless). I believe the extra position magnitude is a typo in Curtis.
